---

- set_fact:
    OS: "linux"
  when: ansible_system == "Linux"

- set_fact:
    OS: "windows"
  when: ansible_os_family == "Windows"

- name: Add host
  checkmk_host:
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    #name: "{{ hostvars['ansible_fqdn'] }}"
    name: "{{ ansible_fqdn }}"
    folder: "{{ cmk_site_default_folder }}/{{ OS }}"
    state: present
  delegate_to: localhost
