---
cmk_agent:
  url:
    deb: "{{ cmk_site_url }}/check_mk/agents/check-mk-agent_{{ cmk_version }}-1_all.deb"
    rpm: "{{ cmk_site_url }}/check_mk/agents/check-mk-agent-{{ cmk_version }}-1.noarch.rpm"
    win: "{{ cmk_site_url }}/check_mk/agents/windows/check_mk_agent.msi"
    win_conf: "check_mk.ini"
  file:
    deb: "{{ cmk_host_linux_tmp }}/check-mk-agent_{{ cmk_version }}-1_all.deb"
    rpm: "{{ cmk_host_linux_tmp }}/check-mk-agent-{{ cmk_version }}-1.noarch.rpm"
    win: "{{ cmk_host_windows_tmp }}\\check_mk_agent.msi"
    win_conf: "C:\\Program Files (x86)\\check_mk\\check_mk.ini"
