---

- name: Remove obsolete {{ obsolete_plugin }}
  win_file:
    path: "{{ plugins_path }}/{{ obsolete_plugin }}"
    state: absent

- name: Remove obsolete config of {{ obsolete_plugin }}
  win_file:
    path: "{{ config_path }}/{{ cmk_plugin_base[ obsolete_plugin ].cfg }}"
    state: absent
  when: cmk_plugin_base[ obsolete_plugin ].cfg is defined
